name = "cf-notion-cache"
main = "src/index.js"
compatibility_date = "2023-01-31"
# node_compat = true
node_compat = false

# this field specifies that the worker
# should be deployed to *.workers.dev
workers_dev = true

# Seems to need to be above the [vars] section
kv_namespaces = [
    { binding = "NOTION_CACHE", preview_id = "a6623ba843e04bf2af34f94025f0a0ec", id = "a4e9d9cbdbdc44d2b8f914e1c9c6e6bc" },
]

# Equivalent of .env vars
# Note: Fill in .dev.vars with the following for development (but don't commit to Git), 
# and also remember to add the secret(s) to Cloudflare settings.
# BUT, don't uncomment the secret(s) below, otherwise those settings will be overwritten when running `wrangler publish`
# See: https://github.com/cloudflare/wrangler2/issues/276#issuecomment-1228631694
[vars]
CLOUDINARY_CLOUD_NAME = "dxsljti9a"
CLOUDINARY_API_KEY = "634166366171861"
# CLOUDINARY_API_SECRET = "{Add as a secret - don't uncomment}"

# [env.dev]
# kv_namespaces = [
#     { binding = "NOTION_CACHE", id = "6baaf919a94c4296aa5f890c638498a1" },
# ]

# [env.production]
# name = "cf-notion-cache"
# kv_namespaces = [
#     { binding = "NOTION_CACHE", id = "a4e9d9cbdbdc44d2b8f914e1c9c6e6bc" },
# ]
